import {writeFileSync,mkdirSync} from 'node:fs';
const IG='https://www.instagram.com/umikaze_mametenchotto/';
const LINE='https://line.me/ti/p/oHE2skCsS';
const MAP='https://goo.gl/maps/Ng7ZphFNs4h2p9de8';
const external='target="_blank" rel="noopener noreferrer"';
const arrow='<span aria-hidden="true">↗</span>';
const icon='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r=".8" fill="currentColor" stroke="none"/></svg>';
const link=(url,label,cls='text-link')=>`<a class="${cls}" href="${url}" ${url.startsWith('https:')?external:''}>${label}${arrow}</a>`;
const photo=(name,alt,cls='',priority=false)=>`<img class="${cls}" src="assets/${name}-960.webp" srcset="assets/${name}-640.webp 640w, assets/${name}-960.webp 960w, assets/${name}.webp 1280w" sizes="(max-width: 700px) 92vw, 55vw" width="1280" height="1280" alt="${alt}" ${priority?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;
const header=page=>`<a class="skip" href="#main">本文へ移動</a><header class="header"><a class="brand" href="index.html"><img src="assets/logo.webp" width="385" height="123" alt="Umikaze-海風 ホーム"></a><nav class="desktop-nav" aria-label="メインナビゲーション">${[['index','海風について'],['menu','お料理'],['guide','愛犬とご一緒に'],['access','店舗案内']].map(([p,n])=>`<a href="${p}.html${p==='index'?'#about':''}" ${p===page?'aria-current="page"':''}>${n}</a>`).join('')}</nav><a class="today" href="${IG}" ${external}>${icon}<span class="today-label">本日の営業・お知らせ</span>${arrow}</a><button class="menu-toggle" aria-expanded="false" aria-controls="mobile-nav"><span class="menu-lines" aria-hidden="true"></span><span class="menu-label">メニュー</span></button><nav id="mobile-nav" class="mobile-nav" aria-label="スマートフォン用ナビゲーション" hidden><p class="eyebrow">EXPLORE UMIKAZE</p><a href="index.html">ホーム <span>01</span></a><a href="menu.html">お料理・お飲み物 <span>02</span></a><a href="guide.html">愛犬とご一緒に <span>03</span></a><a href="access.html">営業時間・アクセス <span>04</span></a>${link(IG,'本日の営業をInstagramで確認','button')}<a class="nav-phone" href="tel:07022186869">ご予約・お問い合わせ　070-2218-6869</a></nav></header>`;
const instagram=()=>`<section class="instagram" id="instagram"><div class="wrap instagram-inner"><div><p class="eyebrow">TODAY AT UMIKAZE</p><h2>今日の海風は、<br>Instagramで。</h2></div><div class="instagram-detail"><p>本日の営業時間、今週のメニュー、<br>イベントのお知らせを投稿しています。<br>ご来店前に、ストーリーズもご確認ください。</p><a class="button light" href="${IG}" ${external}>${icon} Instagramを見る ${arrow}</a><p class="account">@umikaze_mametenchotto</p></div></div></section>`;
const footer=()=>`<footer><div class="wrap footer-main"><div class="footer-brand"><a href="index.html"><img src="assets/logo.webp" width="385" height="123" alt="Umikaze-海風"></a><p>GARDEN CAFE, DOG RUN & HANDMADE</p></div><div class="footer-info"><p>〒355-0072<br>埼玉県東松山市石橋1563-2</p><a class="phone" href="tel:07022186869">070-2218-6869</a><p class="small">ご予約はお電話を優先して承ります。</p><div class="footer-actions">${link(LINE,'LINEでお問い合わせ')}${link(MAP,'Googleマップ')}</div></div><nav class="footer-nav" aria-label="フッターナビゲーション"><a href="index.html">ホーム</a><a href="menu.html">お料理・お飲み物</a><a href="guide.html">愛犬とご一緒に</a><a href="access.html">営業時間・アクセス</a><a href="${IG}" ${external}>Instagram ↗</a></nav></div><div class="wrap footer-bottom"><small>© Umikaze-海風</small><a href="#top">ページの先頭へ ↑</a></div></footer><a class="mobile-today" href="${IG}" ${external}>${icon} 本日の営業・メニューを確認 ${arrow}</a>`;
const dishData=[{n:1,title:'エビチリと中華のおかず',tag:'CHINESE PLATE',desc:'エビチリ、回鍋肉、焼売に、彩りのある小鉢を添えて。',post:'DZ_SgjpvlE6',alt:'エビチリや焼売、小鉢が並ぶ海風の中華定食'},{n:2,title:'大人のお子様ランチ',tag:'A LITTLE NOSTALGIA',desc:'オムライスやナポリタン。懐かしいおいしさを、ひと皿に。',post:'DZrjKGXv8iM',alt:'オムライス、ナポリタン、エビフライなどを盛り合わせたランチ'},{n:3,title:'彩りのワンプレート',tag:'SEASONAL FAVORITES',desc:'お魚や唐揚げ、野菜のおかずを少しずつ楽しむランチ。',post:'DaiUKcRvvlj',alt:'魚のステーキ、唐揚げ、海老しんじょうと野菜のワンプレート'}];
const dishes=()=>`<div class="dish-grid">${dishData.map(d=>`<article class="dish"><a href="${IG}p/${d.post}/" ${external} aria-label="${d.title}の過去の投稿をInstagramで見る"><div class="dish-photo crop-${d.n}"><img src="assets/food-${d.n}.webp" width="${d.n===2?'1152':'1200'}" height="${d.n===1?'1200':d.n===2?'1440':'1500'}" loading="lazy" alt="${d.alt}"><span class="image-arrow" aria-hidden="true">↗</span></div></a><p class="eyebrow">${d.tag}</p><h3>${d.title}</h3><p>${d.desc}</p></article>`).join('')}</div>`;
const subhero=(en,title,desc)=>`<div class="wrap page-heading"><p class="breadcrumb"><a href="index.html">HOME</a><span>/</span>${en}</p><p class="eyebrow">${en}</p><h1>${title}</h1><p class="page-intro">${desc}</p></div>`;
const pages={};
pages.index={title:'Umikaze-海風｜愛犬と過ごす、東松山の庭のカフェ',description:'埼玉県東松山市のガーデンカフェバー Umikaze-海風。天然芝のドッグランと週替わりのお料理。愛犬と一緒に、のんびりとしたひとときを。',body:`<section class="hero"><div class="hero-copy"><p class="eyebrow">HIGASHIMATSUYAMA, SAITAMA</p><h1>きみと、<br>風の通り道で。</h1><p class="hero-lead">愛犬と過ごす、庭のカフェ時間。</p><p class="hero-desc">緑の芝生、空の下のテラス。<br>いつもの毎日から、少しだけひと休み。</p>${link('guide.html','はじめて愛犬とお越しの方へ')}</div><div class="hero-photo">${photo('garden','青いパラソルとハンモックがある、海風の緑豊かなガーデンテラス','',true)}<span class="photo-caption">GOOD DAYS, WITH YOU.</span></div><span class="hero-number">A LITTLE GARDEN. A GOOD TIME.</span></section>
<div class="opening-note wrap"><span>BEFORE YOUR VISIT</span><p>季節・天候により営業時間が変わります。<br class="mobile-only">ご来店前に最新のお知らせをご確認ください。</p>${link(IG,'本日の営業')}</div>
<section class="about wrap" id="about"><div class="about-image reveal">${photo('dog','天然芝の上でのんびり過ごす海風のわんちゃんたち')}<span class="round-stamp" aria-hidden="true">WITH DOGS<br><i>&</i><br>GOOD COMPANY</span></div><div class="about-copy reveal"><p class="eyebrow">WELCOME TO UMIKAZE</p><h2>人も、わんちゃんも。<br>心地よくいられる場所。</h2><p>東松山の小さなガーデンカフェ、Umikaze-海風。<br>お席はすべて、空を感じるテラス席です。</p><p>飼い主さんは、お食事やおしゃべりを。<br>わんちゃんは、緑の芝生でのびのびと。<br>それぞれの「うれしい」が、隣り合う場所に。</p>${link('guide.html','テラスとドッグランについて')}</div></section>
<section class="food-section"><div class="wrap"><div class="section-heading reveal"><div><p class="eyebrow">SOMETHING DELICIOUS</p><h2>今日は、なに食べよう。</h2></div><div><p>訪れるたびに、違うおいしさ。<br>手作りの週替わりメニューをご用意しています。</p>${link('menu.html','お料理・お飲み物を見る')}</div></div>${dishes()}<p class="photo-note">写真はこれまでにご提供したお料理の一例です。今週のメニュー・価格はInstagramでご案内しています。</p></div></section>
<section class="garden-story wrap"><div class="garden-title reveal"><p class="eyebrow">SLOW DOWN, STAY A WHILE</p><h2>ここでは、<br>のんびりがいちばん。</h2></div><div class="garden-wide reveal">${photo('dogrun','フェンスに囲まれた天然芝のドッグランとテラス席')}</div><div class="garden-notes"><div><span>01 / GARDEN</span><h3>空の下、ひと息。</h3><p>カフェだけのご利用も、愛犬とのお出かけにも。思い思いのペースでお過ごしください。</p></div><div><span>02 / HANDMADE</span><h3>うちの子に、ぴったりを。</h3><p>犬のお洋服やお散歩バッグなど、ハンドメイドも同じ敷地に。オーダーメイドのご相談もどうぞ。</p></div><div><span>03 / ACCESS</span><h3>お出かけの途中にも。</h3><p>東松山インター近く。お車は店舗入口の駐車場へ、縦列駐車でお願いいたします。</p>${link('access.html','営業時間・アクセス')}</div></div></section>${instagram()}`};
pages.menu={title:'お料理・お飲み物｜Umikaze-海風',description:'手作りの週替わり料理、カフェドリンク、お酒、わんちゃんメニュー。海風のおいしい時間をご紹介します。',body:`${subhero('FOOD & DRINK','庭で味わう、<br>できたてのひと皿。','しっかりごはんも、気軽なひと休みも。<br>その日の気分で、ゆっくりお楽しみください。')}<section class="wrap menu-feature"><div class="section-heading"><div><p class="eyebrow">WEEKLY SPECIALS</p><h2>週替わりのお楽しみ。</h2></div><p>和・洋・中、いろいろなおいしさを手作りで。<br>下の写真は、過去のメニューからのご紹介です。</p></div>${dishes()}<div class="menu-notice"><p>お料理の内容・価格は週ごとや仕入れによって変わります。<br>現在のメニューはInstagramをご確認ください。</p>${link(IG,'今週のメニューを見る','button')}</div></section>
<section class="menu-list-section"><div class="wrap menu-lists"><div><p class="eyebrow">CAFE TIME</p><h2>お飲み物</h2><p>お食事と一緒に。お散歩のあとの一杯に。</p></div><div class="menu-items"><div><h3>ソフトドリンク</h3><p>コーヒー・紅茶・コーラ<br>オレンジジュース・ウーロン茶<br>ストロベリーシェイク・バナナシェイク<br>海風クリームソーダ</p></div><div><h3>アルコール</h3><p>生ビール・レモンサワー<br>お茶ハイ・ハイボール<br>今週のカクテル</p></div></div></div></section>
<section class="wrap menu-extras"><div class="menu-extra"><span class="eyebrow">A LITTLE BITE</span><h2>軽食も、ゆっくり。</h2><p>ホットサンド、ホットドッグ、唐揚げ、ポテトフライなど。気軽につまめるお料理もご用意しています。</p>${link(`${IG}p/Dbh34W4D2X2/`,'ドリンク・軽食の掲載メニュー')}</div><div class="menu-extra"><span class="eyebrow">FOR YOUR LITTLE FRIEND</span><h2>わんちゃんにも、ごはん。</h2><p>愛犬のための手作りメニューもございます。当日の内容はスタッフへお声がけください。</p>${link('guide.html','愛犬同伴のご案内')}</div></section><div class="wrap quiet-note"><h3>雨の日はテイクアウトで。</h3><p>全席テラス席のため、雨天時のカフェ営業はテイクアウトのみとなります。ご注文や営業状況は、お電話でお問い合わせください。</p>${link('tel:07022186869','070-2218-6869')}</div>${instagram()}`};
pages.guide={title:'愛犬とご一緒に｜Umikaze-海風',description:'天然芝のドッグラン、テラス席と愛犬同伴のご案内。ワクチン接種確認、WanPass、大型犬のご来店について。',body:`${subhero('WITH YOUR DOG','きみの「うれしい」も、<br>大切にしたい。','はじめての方も、いつものお散歩仲間も。<br>安心して過ごしていただくための、海風のご案内です。')}<div class="guide-panorama wrap">${photo('dogrun','天然芝のドッグランとカフェテラス','',true)}<div><p class="eyebrow">GARDEN & DOG RUN</p><h2>芝生の感触。<br>外の空気。<br>いっしょの時間。</h2><p>全席テラス席のカフェに、天然芝のドッグランを併設。わんちゃんとの時間を、気兼ねなく楽しめます。</p></div></div>
<section class="wrap guide-rules"><p class="eyebrow">BEFORE YOUR VISIT</p><h2>ご来店の前に。</h2><div class="rule"><span>01</span><div><h3>小型犬優先のドッグランです。</h3><p>小型犬が安心して過ごせるスペースを大切にしています。大型犬もリード着用でご来店いただけます。ドッグランのご利用については、事前にお店へご相談ください。</p><p>柵のあるスペースです。飛び越えなどがないよう、愛犬から目を離さずにお過ごしください。</p></div></div><div class="rule"><span>02</span><div><h3>狂犬病・混合ワクチンの接種確認を。</h3><p>狂犬病・混合ワクチンの接種状況を確認しています。ご来店前に証明書をご用意ください。受診した動物病院への電話で確認できる場合もございますので、お困りの際はご相談ください。</p></div></div><div class="rule"><span>03</span><div><h3>WanPassの事前登録がおすすめです。</h3><p>ワクチンなどの情報を登録できる「WanPass」に対応しています。来店前に登録を済ませておくと、確認がスムーズです。</p>${link('https://wanpass.me/','WanPassの公式サイトへ')}</div></div></section>
<section class="guide-dog wrap"><div>${photo('dog','芝生の上でくつろぐ2頭のわんちゃん')}</div><div><p class="eyebrow">FEEL AT HOME</p><h2>おなかも、気持ちも、<br>満たされる一日に。</h2><p>わんちゃん用の手作りメニューや、ハンドメイドのお洋服・お散歩バッグもございます。</p><p>愛犬のこと、はじめてのご来店のこと。気になることはお気軽にご相談ください。</p>${link('tel:07022186869','お電話で相談する')}</div></section>
<section class="wrap faq"><p class="eyebrow">QUESTIONS & ANSWERS</p><h2>よくあるご質問</h2><details><summary>犬を連れていなくても利用できますか？</summary><p>もちろんご利用いただけます。お食事やお飲み物を楽しみながら、庭のカフェ時間をお過ごしください。</p></details><details><summary>雨の日も営業していますか？</summary><p>カフェは全席テラス席のため、雨天時はテイクアウトのみの営業です。ハンドメイドのお店は営業しています。天候による変更はInstagramでご確認ください。</p></details><details><summary>予約はできますか？</summary><p>お電話でのご予約を優先して承ります。グループでのご利用は、事前のご予約がおすすめです。<a href="tel:07022186869">070-2218-6869</a>へお電話ください。</p></details></section>${instagram()}`};
pages.access={title:'営業時間・アクセス｜Umikaze-海風',description:'埼玉県東松山市石橋1563-2。東松山インター近く。季節ごとの営業時間、火曜定休、駐車場・ご予約のご案内。',body:`${subhero('VISIT UMIKAZE','お出かけの前に。','季節の移り変わりに合わせて、営業時間が変わります。<br>本日の営業は、Instagramのお知らせをご確認ください。')}<section class="wrap access-grid"><div><p class="eyebrow">OPENING HOURS</p><h2>営業時間</h2><p class="closed-day">定休日：火曜日</p><div class="hours-block"><h3><span>10–6</span> 10月〜6月</h3><dl class="hours"><div><dt>水・木・日</dt><dd>11:00〜19:30<small>L.O. 19:00</small></dd></div><div><dt>月・金・土</dt><dd>11:00〜21:00<small>L.O. 20:30</small></dd></div></dl></div><div class="hours-block"><h3><span>7–9</span> 7月・8月・9月</h3><dl class="hours"><div><dt>朝の営業</dt><dd>6:00〜9:00</dd></div><div><dt>夕方の営業</dt><dd>17:00〜21:00<small>L.O. 20:30</small></dd></div></dl><p class="small">火曜日を除く</p></div><p class="hours-note">上記は基本の営業時間です。気温・天候により変更する場合があります。特に6月・10月は変動しやすいため、最新の営業日・時間をInstagramでご確認ください。</p>${link(IG,'本日の営業を確認する','button')}</div><div class="access-photo">${photo('garden','海風の入口側から見たカフェの庭と青いパラソル','',true)}<div class="address-card"><p class="eyebrow">LOCATION</p><h2>Umikaze-海風</h2><p>〒355-0072<br>埼玉県東松山市石橋1563-2</p>${link(MAP,'Googleマップで開く')}</div></div></section>
<section class="wrap parking-section"><div><p class="eyebrow">PARKING & DIRECTIONS</p><h2>お車でお越しの方へ。</h2></div><div><h3>駐車場は、縦列駐車でお願いします。</h3><p>店舗入口に駐車場がございます。スペースを譲り合って、縦列にお停めください。停め方に迷った場合は、スタッフにお声がけください。</p><h3>店舗前の細い路地は、ゆっくりと。</h3><p>関越道・東松山インター近く。マクドナルド東松山石橋店が目印の交差点からお入りください。店舗前の路地は細いため、お気をつけてお越しください。</p>${link('https://www.instagram.com/stories/highlights/18066018994426376/','駐車場の案内をInstagramで見る')}</div></section>
<section class="reservation wrap" id="reservation"><div><p class="eyebrow">RESERVATION & CONTACT</p><h2>ご予約・お問い合わせ</h2><p>お電話でのご予約を優先して承ります。<br>グループでのご利用は、事前にご相談ください。</p></div><div><a class="reservation-phone" href="tel:07022186869">070-2218-6869 <span>↗</span></a>${link(LINE,'LINEでお問い合わせ','button outline')}<p class="small">お急ぎの場合はお電話をご利用ください。</p></div></section><div class="wrap payment"><h3>お支払いについて</h3><p>現金・クレジットカード・交通系IC・PayPayをご利用いただけます。</p></div>${instagram()}`};
const favicon="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='32' fill='%23256b85'/%3E%3Cpath d='M12 28Q22 18 32 28T52 28M12 41Q22 31 32 41T52 41' fill='none' stroke='white' stroke-width='4'/%3E%3C/svg%3E";
mkdirSync('dist',{recursive:true});
for(const [key,p] of Object.entries(pages)){writeFileSync(`dist/${key}.html`,`<!doctype html>\n<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#fcfbf7"><title>${p.title}</title><meta name="description" content="${p.description}"><meta property="og:title" content="${p.title}"><meta property="og:description" content="${p.description}"><meta property="og:type" content="website"><meta property="og:locale" content="ja_JP"><link rel="icon" type="image/svg+xml" href="${favicon}"><link rel="stylesheet" href="assets/site.css"><link rel="stylesheet" href="assets/layout.css"><script src="assets/site.js" defer></script></head><body id="top">${header(key)}<main id="main">${p.body}</main>${footer()}</body></html>\n`)}
writeFileSync('dist/404.html',`<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ページが見つかりません｜Umikaze-海風</title><body style="font-family:sans-serif;background:#fcfbf7;color:#173e50;padding:12vh 10%;line-height:2"><h1>ページが見つかりませんでした。</h1><p>お探しのページは移動した可能性があります。</p><a href="/" style="color:inherit">海風のホームへ戻る →</a></body></html>`);
console.log('Built 4 pages and a 404 page.');
